FROM maugnorbert/docker_golem_cuda_base

WORKDIR /usr/src/app
VOLUME /usr/src/app/output

RUN apt-get update && apt-get install -y python3-pip python3.8-venv pciutils curl net-tools

COPY requirements.txt .
RUN python3 -m venv /usr/src/app/venv

RUN /usr/src/app/venv/bin/pip install wheel setuptools
RUN /usr/src/app/venv/bin/pip install -r requirements.txt
RUN rm requirements.txt

COPY server.py .
COPY simple_client.py .
